#define ENABLE_MMAL_INLINE_HEADER 1
#define ENABLE_SPS_TIMING 1
#define FRAME_RATE 30
#define INTRAPERIOD FRAME_RATE * 5
#define QUANTISATION_PARAMETER 0
#define IMMUTABLE_OUTPUT 1
#define MS_PER_CHANGE 3